
on:
  schedule:
  - cron:  "*/1 * * * *"
  workflow_dispatch:

jobs:
  synchronization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: synchronization
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/helpfulengineering/devops.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sync_tags: "true"
